alang/urls.py
from django.conf import settings
from django.conf.urls import *
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^todo/', include('todo.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.conf.urls import url
from .views import user_todolists_listview, user_todolist_view

urlpatterns = [
    url(r'^todo_list/(?P<list_id>[0-9]+)/$', user_todolist_view, name='user_todolist_view'),
    url(r'', user_todolists_listview),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User


class ToDo(models.Model):
    list = models.ForeignKey('todo.ToDoList')
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    created_datetime = models.DateTimeField(auto_now=True)
    due_datetime = models.DateTimeField(auto_now=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return '{} ({})'.format(self.title, self.list.title)


class ToDoList(models.Model):
    title = models.CharField(max_length=200)
    owner = models.ForeignKey(User)

    def __str__(self):
        return '{} ({})'.format(self.title.upper(), self.owner)

todo/views.py
from django.contrib.auth.decorators import login_required
from todo.models import ToDoList
from django.views.generic import TemplateView


class TodoListsListView(TemplateView):
    template_name = 'user_todo_lists_listview.html'

    def get_context_data(self, **kwargs):
        context = super(TodoListsListView, self).get_context_data()
        user = self.request.user
        user_lists = ToDoList.objects.filter(owner=user)
        context.update({'user': user, 'user_lists': user_lists})
        return context


class TodoListsView(TemplateView):
    template_name = 'user_todo_list_view.html'

    def get_context_data(self, **kwargs):
        context = super(TodoListsView, self).get_context_data()
        user_list = ToDoList.objects.get(id=kwargs.get('list_id'), owner=self.request.user)
        context.update({'list': user_list})
        return context


user_todolists_listview = login_required(TodoListsListView.as_view())
user_todolist_view = login_required(TodoListsView.as_view())

alang/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block html %}
    <head>
        {% block head %}
            <meta charset="UTF-8">
            <title>Listas de {{ user.first_name }}</title>
            <!-- Latest compiled and minified CSS -->
            <script src="/static/jquery-3.2.1.min.js"></script>
            <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css"/>

            <!-- Optional theme -->
            <link rel="stylesheet" href="/static/bootstrap/css/bootstrap-theme.min.css" />

            <!-- Latest compiled and minified JavaScript -->
            <script src="/static/bootstrap/js/bootstrap.min.js"></script>
        {% endblock %}
    </head>
    <body class="container container-fluid">
    {% block content %}
    {% endblock %}
    </body>
{% endblock %}
</html>

todo/templates/user_todo_list_view.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Lista {{ list.title }}</h1>
        <p>{{ list.description }}</p>
    </div>
</div>
<div class="row">
    <table class="table table-responsive table-bordered">
        <thead>
        <tr>
            <td>Title</td>
            <td>State</td>
            <td>Description</td>
        </tr>
        </thead>
        <tbody>
        {% for todo_item in list.todo_set.all %}
            <tr>
                <td>{{ todo_item.title }}</td>
                <td>{% if todo_item.completed %}(Completado){% else %}(Pendiente){% endif %}</td>
                <td>{{ todo_item.description }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

todo/templates/user_todo_lists_listview.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1>Listas de {{ user.first_name }}</h1>
    </div>
</div>
{% for list in user_lists %}
    <div class="row">
        <div class="col-md-12">
            <a href='{% url "user_todolist_view" list.id %}'><h2>{{ list.title }}</h2></a>
            <p>{{ list.description }}</p>
        </div>
    </div>
{% endfor %}
{% endblock %}